### ISSUE TITLE
500 Internal server error on accessing Kanban States

### ISSUE THREAD

**Issue by kksure** [samchen2009/ekanban#30] opened 2013-07-18 14:30 UTC
I'm using redmine 2.3.0 version

I followed the readme file successfully till
Administration -> Setting -> Project -> Default enabled modules for new projects -> Check "Kanban"

When I click on Administration - > 'Kanban States' . The page shows an internal error. 

The following is the log:

Started GET "/kanban_states/setup" for 10.5.73.15 at Thu Jul 18 09:19:43 -0500 2013
Processing by KanbanStatesController#setup as HTML
  Current user: testuser (id=81)
  Rendered plugins/ekanban/app/views/kanban_states/_state_list.html.haml (11.0ms)
  Rendered plugins/ekanban/app/views/common/_tabs.html.erb (13.6ms)
  Rendered plugins/ekanban/app/views/kanban_states/index.html.haml within layouts/base (14.2ms)
Completed 500 Internal Server Error in 22ms

ActionView::Template::Error (undefined method `name' for nil:NilClass):
    20:             %td=h(s.is_default)
    21:             %td=h(s.is_initial)
    22:             %td=h(s.is_closed)
    23:             %td=h(s.kanban_stage.name)
    24:             %td=h(s.description)
    25:             %td{:class => "buttons"}
    26:               %em.info.error{:style => "display:none"} "Destroy failed!"
  plugins/ekanban/app/views/kanban_states/_state_list.html.haml:23:in`_plugins_ekanban_app_views_kanban_states__state_list_html_haml__731033271_70173008245080'
  plugins/ekanban/app/views/kanban_states/_state_list.html.haml:17:in `each'
  plugins/ekanban/app/views/kanban_states/_state_list.html.haml:17:in`_plugins_ekanban_app_views_kanban_states__state_list_html_haml__731033271_70173008245080'
  plugins/ekanban/app/views/kanban_states/_state_list.html.haml:4:in `each'
  plugins/ekanban/app/views/kanban_states/_state_list.html.haml:4:in`_plugins_ekanban_app_views_kanban_states__state_list_html_haml__731033271_70173008245080'
  actionpack (3.2.13) lib/action_view/template.rb:145:in `send'
  actionpack (3.2.13) lib/action_view/template.rb:145:in`render'
  activesupport (3.2.13) lib/active_support/notifications.rb:125:in `instrument'
  actionpack (3.2.13) lib/action_view/template.rb:143:in`render'
  actionpack (3.2.13) lib/action_view/renderer/partial_renderer.rb:265:in `render_partial'
  actionpack (3.2.13) lib/action_view/renderer/partial_renderer.rb:238:in`render'
  actionpack (3.2.13) lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
  activesupport (3.2.13) lib/active_support/notifications.rb:123:in`instrument'
  activesupport (3.2.13) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (3.2.13) lib/active_support/notifications.rb:123:in`instrument'
  actionpack (3.2.13) lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
  actionpack (3.2.13) lib/action_view/renderer/partial_renderer.rb:237:in`render'
  actionpack (3.2.13) lib/action_view/renderer/renderer.rb:41:in `render_partial'
  actionpack (3.2.13) lib/action_view/renderer/renderer.rb:15:in`render'
  actionpack (3.2.13) lib/action_view/helpers/rendering_helper.rb:24:in `render_without_haml'
  haml (4.0.2) lib/haml/helpers/action_view_mods.rb:12:in`render'
  plugins/ekanban/app/views/common/_tabs.html.erb:23:in `_plugins_ekanban_app_views_common__tabs_html_erb__656382639_70173005056840'
  plugins/ekanban/app/views/common/_tabs.html.erb:22:in`each'
  plugins/ekanban/app/views/common/_tabs.html.erb:22:in `_plugins_ekanban_app_views_common__tabs_html_erb__656382639_70173005056840'
  actionpack (3.2.13) lib/action_view/template.rb:145:in`send'
  actionpack (3.2.13) lib/action_view/template.rb:145:in `render'
  activesupport (3.2.13) lib/active_support/notifications.rb:125:in`instrument'
  actionpack (3.2.13) lib/action_view/template.rb:143:in `render'
  actionpack (3.2.13) lib/action_view/renderer/partial_renderer.rb:265:in`render_partial'
  actionpack (3.2.13) lib/action_view/renderer/partial_renderer.rb:238:in `render'
  actionpack (3.2.13) lib/action_view/renderer/abstract_renderer.rb:38:in`instrument'
  activesupport (3.2.13) lib/active_support/notifications.rb:123:in `instrument'
  activesupport (3.2.13) lib/active_support/notifications/instrumenter.rb:20:in`instrument'
  activesupport (3.2.13) lib/active_support/notifications.rb:123:in `instrument'
  actionpack (3.2.13) lib/action_view/renderer/abstract_renderer.rb:38:in`instrument'
  actionpack (3.2.13) lib/action_view/renderer/partial_renderer.rb:237:in `render'
  actionpack (3.2.13) lib/action_view/renderer/renderer.rb:41:in`render_partial'
  actionpack (3.2.13) lib/action_view/renderer/renderer.rb:15:in `render'
  actionpack (3.2.13) lib/action_view/helpers/rendering_helper.rb:24:in`render_without_haml'
  haml (4.0.2) lib/haml/helpers/action_view_mods.rb:10:in `render'
  haml (4.0.2) lib/haml/helpers.rb:89:in`non_haml'
  haml (4.0.2) lib/haml/helpers/action_view_mods.rb:10:in `render'

Let me know if you need any specific details. I couldn't figure out what went wrong. Could you please help.

**Comment by kksure** [comment] 2013-08-01 04:49
Did someone get a chance to look into this? Please help.

**Comment by samchen2009** [comment] 2013-08-14 15:53
"ActionView::Template::Error (undefined method name' for nil:NilClass):" meant your kanban state doesn't belong to a  Kanban Stage, did you add some stage at 'Administration' -> 'Kanban States' -> 'Stages' tab ?

**Comment by kksure** [comment] 2013-08-15 10:09
Well thats what I was trying to do. But as soon as I click on 'Administration' -> Kanban States, I get the error. I don't even see a 'Stages' tab. I see a 500 error. Is there any other way I can set it up?

**Comment by kksure** [comment] 2013-08-19 18:41
Hi, Do you need more details here. Please let me know how I can help you identify the issue.
I really like the plugin and would like to use asap.

**Comment by samchen2009** [comment] 2013-08-21 05:28
Sorry for late reply. Let me try to improve the error handling ...

**Comment by samchen2009** [comment] 2013-08-21 06:15
Fixed in 776f5860c899d9c932d8932542ee4f3dc8f920ee. The cause may be you created kanban state before kanban stages created. I add error handling for this case so that you can enter the state setup page then you're able to setup it properly. Please do it otherwise, other place may crash as well since they may uses kanban stage.

**Closed as completed by samchen2009** 2013-08-21 06:15 UTC
